### PR TITLE
Add fileOrder for sortBy option

### PR DESCRIPTION
**Pull request by manufaktor**
This way the order will be "as is" in your CSS.

### CODE REVIEW

**Comment by Aratramba** [comment]
Haven't yet tested this but at first sight I see no changes to any template where I think there should be. This way source.fileOrder isn't actually used, right?

**Comment by manufaktor** [comment]
It's supposed to be used in the sortBy option, like any other yaml attribute. Isn't this the correct way?

**Comment by Aratramba** [comment]
I see, you're absolutely right, this is the correct way. I'm adding tests for the (previously undocumented) sortBy now.

**Comment by Aratramba** [comment]
just curious, in what situation would you want to use the fileorder for your styleguide?

**Comment by manufaktor** [comment]
We write Sass modules and import them in a certain order. The end product is then processed with styleguide.js. This way we don't need to have an explicit order attribute in the Yaml, which would get time-consuming to maintain.

**Comment by Aratramba** [comment]
ah ok. Published it to npm, so you should be good to go.

**Comment by manufaktor** [comment]
thx!

**Pull request merged**
